# ResearcherRAG Documentation Site Configuration
# GitHub Pages + Jekyll

# Site settings
title: ResearcherRAG Documentation
description: "PRISMA 2020 + RAG for systematic literature reviews. Build rigorous, AI-powered research systems in days, not months."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://hosungyou.github.io/researcherRAG" # Update with your GitHub Pages URL

# Theme
theme: just-the-docs
color_scheme: light

# Search (Enhanced)
search_enabled: true
search:
  heading_level: 2
  previews: 5
  preview_words_before: 8
  preview_words_after: 12
  tokenizer_separator: /[\s\-/]+/
  rel_url: true
  button: true

# Mermaid diagrams support
mermaid:
  version: "10.6.0"

# Navigation
nav_sort: case_insensitive
nav_enabled: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer
footer_content: "Copyright &copy; 2025 ResearcherRAG. Built with <a href=\"https://github.com/just-the-docs/just-the-docs\">Just the Docs</a>."

# Aux links (top right)
aux_links:
  "GitHub":
    - "https://github.com/HosungYou/researcherRAG"
  "Issues":
    - "https://github.com/HosungYou/researcherRAG/issues"

# Heading anchors
heading_anchors: true

# Collections
collections:
  stages:
    permalink: "/:collection/:path/"
    output: true
  reference:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    stages:
      name: 5-Stage Workflow
      nav_order: 3
    reference:
      name: Reference
      nav_order: 4

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-metadata

# Exclude
exclude:
  - README.md
  - LICENSE
  - scripts/
  - prompts/
  - examples/
  - templates/
  - workshop/
  - interfaces/
  - node_modules/
  - vendor/

# GitHub metadata (for edit links)
github:
  repository_url: "https://github.com/HosungYou/researcherRAG"
  edit_on_github: true
  edit_on_github_text: "Edit this page on GitHub"
  edit_on_github_branch: "main"
